Repository auxmoney/OpentracingBundle-amqplib-RabbitMq, pull requests merged in 2020-04, with the labels that each got.

#2 Initial release
  .codacy.yml
  .github/workflows/release.yml
  .gitignore
  .releaserc.json
  .travis.yml
  CONTRIBUTING.md
  Consumer/Consumer.php
  DependencyInjection/AmqplibRabbitMqConsumerCompilerPass.php
  DependencyInjection/AmqplibRabbitMqProducerCompilerPass.php
  DependencyInjection/OpentracingAmqplibRabbitMqExtension.php
  EventSubscriber/AfterMessageProcessingSubscriber.php
  EventSubscriber/BeforeMessageProcessingSubscriber.php
  EventSubscriber/FinishCommandSpanSubscriberDecorator.php
  EventSubscriber/StartCommandSpanSubscriberDecorator.php
  MAINTAINING.md
  OpentracingAmqplibRabbitMqBundle.php
  Producer/Producer.php
  README.md
  Resources/config/services.yaml
  Tests/Unit/Consumer/ConsumerTest.php
  Tests/Unit/DependencyInjection/AmqplibRabbitMqConsumerCompilerPassTest.php
  Tests/Unit/DependencyInjection/AmqplibRabbitMqProducerCompilerPassTest.php
  Tests/Unit/DependencyInjection/OpentracingAmqplibRabbitMqExtensionTest.php
  Tests/Unit/EventSubscriber/AfterMessageProcessingSubscriberTest.php
  Tests/Unit/EventSubscriber/BeforeMessageProcessingSubscriberTest.php
  Tests/Unit/EventSubscriber/FinishCommandSpanSubscriberDecoratorTest.php
  Tests/Unit/EventSubscriber/StartCommandSpanSubscriberDecoratorTest.php
  Tests/Unit/OpenTracingAmqplibRabbitMqBundleTest.php
  Tests/Unit/Producer/ProducerTest.php
  composer.json
  phpcs.xml
  phpstan.neon
  phpunit.xml.dist
Labels: enhancement

#4 chore: add functional tests
  .travis.yml
  Tests/Functional/FunctionalTest.expected.yaml
  Tests/Functional/FunctionalTest.php
  Tests/Functional/Scripts/requireAdditionalVendors.sh
  Tests/Functional/TestProjectFiles/default/.env
  Tests/Functional/TestProjectFiles/default/config/packages/old_sound_rabbit_mq.yaml
  Tests/Functional/TestProjectFiles/default/config/services.yaml
  Tests/Functional/TestProjectFiles/default/src/Command/TestCommand.php
  Tests/Functional/TestProjectFiles/default/src/Consumer/TestConsumer.php
  composer.json
Labels: quality

#5 chore: functional tests from forks
  .travis.yml
  Tests/Functional/Scripts/requireAdditionalVendors.sh
Labels: bug, quality
